# Proyecto RappiPlus: de datos a decisiones de negocio

**Introducción**


El objetivo de este proyecto es evaluar el desempeño del servicio **RappiPlus** para apoyar **decisiones de negocio basadas en datos**.

Se trabajan con múltiples datasets del negocio:

- **rappiplus_orders_raw.csv** → información de pedidos, precios, descuentos y revenue  
- **rappiplus_catalog.csv** → costos de productos, categorías y proveedores  
- **rappiplus_marketing_spend.csv** → inversión en marketing por canal y país  
- **events / users / user_activity (SQL)** → comportamiento del usuario dentro de la plataforma  
- **experiment_checkout_ui.csv** → resultados de un experimento A/B en el checkout  

El análisis sigue una lógica clara y progresiva:

1. 🔍 Evaluar si podemos confiar en los datos (calidad de datos en Python) 

2. 💰 Analizar si el negocio es rentable (revenue, costos y profit)  

3. 🛒 Entender dónde se pierden los usuarios (funnel de conversión)  

4. 🔁 Evaluar si los usuarios regresan (retención por cohortes)  

5. 🧪 Validar si los cambios generan impacto (test estadístico)  

6. 📊 Comunicar los resultados (dashboard en BI)  

A lo largo del proyecto, se transforman datos en insights para responder preguntas clave del negocio y proponer **recomendaciones accionables**.

---

## 🔹 Paso 1: Cargar y validar la calidad de los datos

---

### 1.1 Carga de datos y vista rápida

**🎯 Objetivo:** Familiarizarte con la estructura de los datasets del negocio antes de analizarlos.

**Instrucciones:**

- Importa las librerías necesarias
- Carga los archivos:
  - `rappiplus_orders_raw.csv`
  - `rappiplus_catalog.csv`
  - `rappiplus_marketing_spend.csv`
- Guarda los DataFrames en:
  - `orders`, `catalog`, `marketing`
- Explora cada dataset.

---

In [17]:
# importar librerías
import pandas as pd

In [31]:
# cargar archivos
orders =  pd.read_csv("https://practicum-content.s3.amazonaws.com/datasets/rappiplus_orders_raw.csv") # tu código aquí
catalog = pd.read_csv("https://practicum-content.s3.amazonaws.com/datasets/rappiplus_catalog.csv") # tu código aquí
marketing = pd.read_csv("https://practicum-content.s3.amazonaws.com/datasets/rappiplus_marketing_spend.csv") # tu código aquí

In [19]:
# explorar datasets
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25100 entries, 0 to 25099
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_pedido           25100 non-null  object
 1   id_usuario          25100 non-null  object
 2   fecha_hora_pedido   25100 non-null  object
 3   pais                24800 non-null  object
 4   dispositivo         25080 non-null  object
 5   fuente_referencia   25070 non-null  object
 6   nombre_producto     25070 non-null  object
 7   categoria_producto  25020 non-null  object
 8   cantidad            25050 non-null  float64
 9   precio_unitario     25050 non-null  float64
 10  monto_descuento     25050 non-null  float64
 11  monto_total         25100 non-null  float64
dtypes: float64(4), object(8)
memory usage: 2.3+ MB

In [20]:
orders.head()

,id_pedido,id_usuario,fecha_hora_pedido,pais,dispositivo,fuente_referencia,nombre_producto,categoria_producto,cantidad,precio_unitario,monto_descuento,monto_total
0,order_0,user_6993,2025-05-22,Argentina,desktop,organic,Jacket-Winter-M,Moda,2.0,332.69,0.0,665.37
1,order_1,user_1329,2025-06-15,Mexico,desktop,paid_search,Tablet-Standard-64GB,Electronica,1.0,176.86,5.0,171.86
2,order_2,user_3194,2025-05-02,Argentina,desktop,social,Blender-XL-Red,Hogar,2.0,102.99,10.0,195.99
3,order_3,user_4510,2025-06-09,Colombia,mobile,social,Tablet-Standard-64GB,Electronica,1.0,257.87,15.0,242.87
4,order_4,user_5044,2025-03-30,Argentina,desktop,paid_search,Blender-XL-Red,Hogar,1.0,336.28,0.0,336.28

In [21]:
orders.describe()

           cantidad  precio_unitario  monto_descuento   monto_total
count  25050.000000     25050.000000     25050.000000  2.510000e+04
mean       7.092735       259.305549         4.500798  2.072680e+03
std      296.277003       138.726461         5.223010  9.894995e+04
min       -2.000000        20.030000         0.000000 -4.926500e+02
25%        1.000000       138.377500         0.000000  1.805075e+02
50%        2.000000       258.715000         0.000000  3.417500e+02
75%        2.000000       380.332500        10.000000  5.185800e+02
max    20000.000000       499.960000        15.000000  8.840200e+06

In [22]:
# dataset catalog 
catalog.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   nombre_producto     7 non-null      object
 1   categoria_producto  7 non-null      object
 2   costo_unitario      7 non-null      float64
 3   proveedor           7 non-null      object
dtypes: float64(1), object(3)
memory usage: 352.0+ bytes

In [23]:
catalog.head(9)

,nombre_producto,categoria_producto,costo_unitario,proveedor
0,Laptop-Gaming-16GB,Electrónica,280.68,"Fuller, Pena and Myers"
1,Phone-Pro-128GB,Electrónica,10.12,King Ltd
2,Tablet-Standard-64GB,Electrónica,25.21,Bowers LLC
3,Blender-XL-Red,Hogar,176.64,Long-Reid
4,Vacuum-Pro-Black,Hogar,16.60,"Rivera, Carr and Finley"
5,Sneakers-Urban-42,Moda,17.21,Greene-Smith
6,Jacket-Winter-M,Moda,189.31,Mcmillan-Rhodes

In [24]:
catalog.describe()

       costo_unitario
count        7.000000
mean       102.252857
std        111.011563
min         10.120000
25%         16.905000
50%         25.210000
75%        182.975000
max        280.680000

In [25]:
# Dataset marketing
marketing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1620 entries, 0 to 1619
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   fecha       1620 non-null   object
 1   pais        1620 non-null   object
 2   id_campaña  1620 non-null   object
 3   canal       1519 non-null   object
 4   gasto       1620 non-null   float64
dtypes: float64(1), object(4)
memory usage: 63.4+ KB

In [26]:
marketing.head()

        fecha      pais            id_campaña        canal    gasto
0  2025-01-01    Mexico        organic_Mexico      organic  2446.25
1  2025-01-01    Mexico    paid_search_Mexico  paid_search  2704.34
2  2025-01-01    Mexico         social_Mexico       social  2045.01
3  2025-01-01  Colombia      organic_Colombia      organic  2597.21
4  2025-01-01  Colombia  paid_search_Colombia  paid_search  1771.40

In [27]:
marketing.describe()

            gasto
count  1620.00000
mean   1772.74292
std     734.43294
min     501.11000
25%    1128.03000
50%    1782.42500
75%    2420.68500
max    2999.36000

---

### Revisión y calidad de datos

**🎯 Objetivo:** Detectar y corregir problemas en los datos que puedan afectar el análisis de revenue, costos y rentabilidad.

Se revisan los 3 datasets
- Validar y convertir fechas al formato correcto  
- Revisar variables numéricas (sin negativos o ceros inválidos)  
- Verificar consistencia de montos  
- Eliminar duplicados  
- Revisar variables categóricas 

---

In [28]:
# Convertir al formato datetime y detectar errores 

orders['fecha_hora_pedido'] = pd.to_datetime(orders['fecha_hora_pedido'], errors='coerce')
marketing['fecha'] = pd.to_datetime (marketing['fecha'], errors='coerce')

In [29]:

# Reportar valores invalidos 

# orders
invalid_dates_orders = orders['fecha_hora_pedido'].isna().sum()
print(f"Fechas inválidas: {invalid_dates_orders}")
# marketing 
invalid_dates_marketing = marketing['fecha'].isna().sum()
print(f"Fechas inválidas: {invalid_dates_marketing}")

Fechas inválidas: 0
Fechas inválidas: 0

In [32]:
# Filas inválidas
invalid_row_1 = orders.isna().sum()
print(invalid_row_1)

id_pedido               0
id_usuario              0
fecha_hora_pedido       0
pais                  300
dispositivo            20
fuente_referencia      30
nombre_producto        30
categoria_producto     80
cantidad               50
precio_unitario        50
monto_descuento        50
monto_total             0
dtype: int64

In [33]:
invalid_row_2 = catalog.isna().sum()
print(invalid_row_2)

nombre_producto       0
categoria_producto    0
costo_unitario        0
proveedor             0
dtype: int64

In [34]:
invalid_row_3 = marketing.isna().sum()
print(invalid_row_3)

fecha           0
pais            0
id_campaña      0
canal         101
gasto           0
dtype: int64

In [ ]:
#Resultados en tipo de dato 
marketing.info()
orders.info()

In [ ]:
# Revisando columnas numéricas 
orders.describe()

In [ ]:
marketing.describe()

In [47]:
print(marketing["gasto"].head(10))

0    2446.25
1    2704.34
2    2045.01
3    2597.21
4    1771.40
5     833.38
6    1365.62
7    1282.65
8    1534.69
9    2537.38
Name: gasto, dtype: float64

In [ ]:
# Máscara de valores

mascara = (orders["cantidad"] <= 0) | (orders["monto_total"] <= 0)

# Contar cuántas filas cumplen la condición
filas_problematicas = mascara.sum()
print("Filas problemáticas detectadas:", filas_problematicas)

# Eliminar las filas problemáticas
orders = orders[~mascara]


# Confirmar resultado
print("Registros originales:", len(orders) + filas_problematicas)
print("Registros finales:", len(orders))

In [ ]:
# Verificar consistencia de montos 
orders["check_monto"] = (orders["cantidad"] * orders["precio_unitario"]) - orders["monto_descuento"]

# Comparar con monto_total
inconsistencias = (orders["check_monto"] != orders["monto_total"]).sum()

print("Filas inconsistentes:", inconsistencias)

# Eliminar filas inconsistentes
# --
#Se decide no eliminar las inconsistencias para entender cómo se comportan las ventas

In [38]:
#Eliminación de duplicados
duplicates = orders.duplicated().sum()
total_filas = len(orders)
porcentaje = (duplicates / total_filas) * 100
print(f"Filas duplicadas: {duplicates} ({porcentaje:.2f}%)")
orders_limpio = orders.drop_duplicates()
print(f"Duplicados eliminados: {duplicates}")

Filas duplicadas: 100 (0.40%)
Duplicados eliminados: 100

In [39]:
print("Registros finales:", len(orders_limpio))

Registros finales: 25000

In [56]:
# Se conservan valores vacios de filas con montos validos para Análisis
# Porcentaje de vacios 
valores_vacios = (orders_limpio.isna().sum() / len(orders_limpio) * 100).round(2)
print(valores_vacios)

id_pedido             0.00
id_usuario            0.00
fecha_hora_pedido     0.00
pais                  1.20
dispositivo           0.08
fuente_referencia     0.12
nombre_producto       0.12
categoria_producto    0.32
cantidad              0.20
precio_unitario       0.20
monto_descuento       0.20
monto_total           0.00
dtype: float64

---
**📦 Exportación**: Una vez finalizada la limpieza, se exportan los datasets para utilizarlos en la última etapa del proyecto.

In [41]:
# exportar datasets
orders_limpio.to_csv('orders_clean.csv', index=False)
catalog.to_csv('catalog_clean.csv', index=False)
marketing.to_csv('marketing_clean.csv', index=False)

---

## 🔹 Paso 2: Analizar si el negocio es rentable

### 2.1 Cálculo de KPIs principales

**🎯 Objetivo:** Calcular los indicadores clave del negocio para evaluar ingresos, costos y rentabilidad.

Se usan los 3 datasets (`orders`, `catalog`, `marketing_spend`):

**📊 Parte 1: Rentabilidad del negocio**
- ¿Cuál es el ingreso total (revenue)? 
- ¿Cuál es el costo total? 
- ¿Cuánto se ha invertido en marketing? 
- ¿El negocio es rentable? (calcular profit)  

---

**📈 Parte 2: Comportamiento de ventas**
- ¿Cuál es el ticket promedio por orden? 
- ¿Cuál es la cantidad promedio de productos por orden? 
- ¿Cuál es el producto más vendido?
- ¿Cuánto se ha gastado en marketing por canal?

In [42]:
# Paso 1 Rentabilidad del negocio
# KPIs principales:

In [43]:
# Revenue total
revenue_total = orders_limpio["monto_total"].sum()
print(f"Revenue total: ${revenue_total:,.2f}")

Revenue total: $51,987,462.26

In [44]:
# Costo total
orders_con_costo = orders_limpio.merge(catalog[["nombre_producto","costo_unitario"]], on="nombre_producto", how="left")
orders_con_costo["costo_total"] = orders_con_costo["costo_unitario"] * orders_con_costo["cantidad"]

costo = orders_con_costo["costo_total"].sum()
print(f"Costo total: ${costo:,.2f}")

Costo total: $43,124,018.41

In [45]:

# Inversión en marketing
inversion_marketing = marketing["gasto"].sum()
print(f"Inversión en marketing: ${inversion_marketing:,.2f}")

Inversión en marketing: $2,871,843.53

In [46]:
# Profit

# Ganancia bruta
profit_bruto = revenue_total - costo 
print(f"Profit : ${profit_bruto:,.2f}")
margen_profit = profit_bruto / revenue_total
print(f"margen profit: {margen_profit:,.2f}%")

Profit : $8,863,443.85
margen profit: 0.17%

In [ ]:
# Ganancia neta 
profit_neto = revenue_total - costo - inversion_marketing
print(f"Profit : ${profit_neto:,.2f}")
margen_profit = profit_neto / revenue_total
print(f"margen profit: {margen_profit:,.2f}%")

In [ ]:
# Paso 2 Comportamiento de ventas

In [ ]:
# Calcular ticket promedio
ticket_promedio = orders["monto_total"].mean()

print(f"Ticket promedio: ${ticket_promedio:,.2f}")

In [ ]:
# Calcular cantidad promedio 
cantidad_promedio = orders["cantidad"].mean()


print(f"Cantidad promedio: {cantidad_promedio:,.2f}")

In [ ]:
# Agrupar por producto y sumar cantidades
ventas_por_producto = orders.groupby("nombre_producto")["cantidad"].sum()

# Ordenar de mayor a menor
ventas_por_producto = ventas_por_producto.sort_values(ascending=False)

# Mostrar el producto más vendido
producto_top = ventas_por_producto.index[0]
cantidad_top = ventas_por_producto.iloc[0]

print("Producto más vendido:", producto_top)
print("Cantidad total vendida:", cantidad_top)

In [ ]:
gasto_marketing_canal = marketing.groupby("canal")["gasto"].sum()

print(f"{gasto_marketing_canal:}")

---

## 🔹 Paso 3: Entender dónde se pierden los usuarios (funnel de conversión)

**🎯 Objetivo:** Analizar el comportamiento de los usuarios para identificar en qué etapa del proceso se pierden.


⚙️**Conexión a la base de datos**:  
Se ejecuta la línea de configuración para conectar con la base de datos y aplicar consultas SQL en la tabla **events**.

---

**📊 Parte 1: Construcción del funnel**
- ¿Cuántos usuarios llegan a cada etapa del funnel?  
- Se calcula el número de usuarios únicos por `nombre_evento`  
- Se ordenan los eventos según el flujo del usuario  

---

**📉 Parte 2: Análisis de conversión**
- Se calcula la tasa de conversión entre cada paso del funnel  
- Se identifica en qué etapa se pierde la mayor cantidad de usuarios  
- ¿Cuál es la tasa de conversión final?
---

In [17]:
import pandas as pd
from sqlalchemy import create_engine

# ======================
# Conexión (NO modificar)
# ======================
db_config = {
    'user': 'practicum_student',
    'pwd': 'QnmDH8Sc2TQLvy2G3Vvh7',
    'host': 'yp-trainers-practicum.cluster-czs0gxyx2d8w.us-east-1.rds.amazonaws.com',
    'port': 5432,
    'db': 'data-analyst-production-db-en'
}

connection_string = 'postgresql://{}:{}@{}:{}/{}'.format(
    db_config['user'],
    db_config['pwd'],
    db_config['host'],
    db_config['port'],
    db_config['db']
)

engine = create_engine(connection_string, connect_args={'sslmode':'require'})

In [18]:
# Explorar tabla events
# =========================
query_events = '''
SELECT *
FROM events;
'''
events = pd.read_sql(query_events, con=engine)
events.head()

,id_usuario,id_sesion,nombre_evento,timestamp_evento,pais,dispositivo,fuente_referencia,categoria_producto
0,user_6772,6a97f2af-32ae-4186-8c92-04025be1a27b,first_visit,2025-05-17,Colombia,desktop,organic,Moda
1,user_5883,369b767c-1c33-4b2f-a652-c7c0ef92cfc9,add_to_cart,2025-02-23,Mexico,mobile,social,Hogar
2,user_5946,60039041-e78b-474c-87b3-c0b7e9c30708,add_payment_info,2025-05-15,Colombia,desktop,social,Electronica
3,user_827,18252a64-f389-4ef7-9e58-dadad4a3491e,purchase,2025-03-31,Mexico,mobile,social,Moda
4,user_2361,221b364e-cdc5-4668-b698-18d5ba849a67,first_visit,2025-01-22,Argentina,desktop,paid_search,Electronica

In [ ]:
# PARTE 1: Totales del funnel
# ======================

query_totals = '''
    SELECT 
    nombre_evento,
    COUNT(DISTINCT id_usuario) AS usuarios_unicos
FROM Events
GROUP BY nombre_evento
ORDER BY usuarios_unicos DESC;;
'''

totals = pd.read_sql(query_totals, con=engine)
totals

In [ ]:

# PARTE 2: Conversiones
# ======================

query_conversion = '''
WITH conversiones AS (
    SELECT 
        e1.nombre_evento AS etapa_actual,
        e2.nombre_evento AS etapa_siguiente,
        ROUND((e2.usuarios * 1.0 / e1.usuarios) * 100, 2) AS tasa_conversion
    FROM (
        SELECT nombre_evento, COUNT(DISTINCT id_usuario) AS usuarios
        FROM Events
        GROUP BY nombre_evento
    ) e1
    JOIN (
        SELECT nombre_evento, COUNT(DISTINCT id_usuario) AS usuarios
        FROM Events
        GROUP BY nombre_evento
    ) e2 ON e2.nombre_evento > e1.nombre_evento
)
SELECT 
    etapa_actual,
    etapa_siguiente,
    tasa_conversion
FROM conversiones
ORDER BY tasa_conversion ASC
LIMIT 1;

'''

conversion = pd.read_sql(query_conversion, con=engine)
conversion

---

## 🔹 Paso 4: Evaluar si los usuarios regresan (retención por cohortes)

**🎯 Objetivo:** Analizar la retención de usuarios para entender si regresan después de registrarse.

**Tablas**

- `users` 
- `user_activity` 

---
1. Se identifica la cohorte de cada usuario según el **mes de registro**.


2. Se calcula la retención semanal: cuántos usuarios **se mantienen activos** en cada semana desde su registro.
   - `retenido_w1`: usuarios activos en la semana 1  
   - `retenido_w2`: usuarios activos en la semana 2  
   - `retenido_w3`: usuarios activos en la semana 3  


3. Se calcula el porcentaje de retención para cada semana, dividiendo los usuarios retenidos entre los clientes iniciales de la cohorte:  
   - `semana_1`: porcentaje de usuarios retenidos en la semana 1  
   - `semana_2`: porcentaje de usuarios retenidos en la semana 2  
   - `semana_3`: porcentaje de usuarios retenidos en la semana 3  

Se revisa que la columna de fecha esté en formato correcto (`DATE`).  
Se realiza la conversión usando: `CAST(fecha_registro AS DATE)`

In [ ]:
# Explorar tabla users
# =========================
query_users = '''
SELECT *
FROM users;
'''
users = pd.read_sql(query_users, con=engine)
users.head(3)

In [ ]:
# Explorar tabla user_activity
# =========================
query_user_activity = '''
SELECT *
FROM user_activity;
'''
user_activity = pd.read_sql(query_user_activity, con=engine)
user_activity.head(5)

In [19]:
# Retención por cohortes
# ======================

query_cohort_retention_final = '''
WITH cohortes AS (
    SELECT 
        DATE_TRUNC('month', CAST(fecha_registro AS DATE)) AS mes_cohorte,
        COUNT(DISTINCT id_usuario) AS usuarios_iniciales
    FROM users
    GROUP BY mes_cohorte
),
retencion AS (
    SELECT 
        DATE_TRUNC('month', CAST(u.fecha_registro AS DATE)) AS mes_cohorte,
        COUNT(DISTINCT CASE WHEN ua.dias_despues_registro BETWEEN 0 AND 7 THEN u.id_usuario END) AS retenido_w1,
        COUNT(DISTINCT CASE WHEN ua.dias_despues_registro BETWEEN 8 AND 15 THEN u.id_usuario END) AS retenido_w2,
        COUNT(DISTINCT CASE WHEN ua.dias_despues_registro BETWEEN 16 AND 23 THEN u.id_usuario END) AS retenido_w3
    FROM users u
    JOIN user_activity ua ON u.id_usuario = ua.id_usuario
    WHERE ua.activo = 1
    GROUP BY mes_cohorte
)
SELECT 
    r.mes_cohorte,
    ROUND((r.retenido_w1 * 1.0 / c.usuarios_iniciales) * 100, 2) AS semana_1,
    ROUND((r.retenido_w2 * 1.0 / c.usuarios_iniciales) * 100, 2) AS semana_2,
    ROUND((r.retenido_w3 * 1.0 / c.usuarios_iniciales) * 100, 2) AS semana_3
FROM retencion r
JOIN cohortes c ON r.mes_cohorte = c.mes_cohorte
ORDER BY r.mes_cohorte;;
'''

# Ejecutar la consulta
cohorte_final = pd.read_sql(query_cohort_retention_final, con=engine)
cohorte_final

                mes_cohorte  semana_1  semana_2  semana_3
0 2025-01-01 00:00:00+00:00     42.84     41.06     40.32
1 2025-02-01 00:00:00+00:00     42.31     42.17     43.98
2 2025-03-01 00:00:00+00:00     41.38     43.09     42.18
3 2025-04-01 00:00:00+00:00     42.34     43.40     41.28
4 2025-05-01 00:00:00+00:00     41.20     40.07     41.85

---

## 🔹 Paso 5: Validar si los cambios generan impacto (test estadístico)

🎯 **Objetivo:** Evaluar si la modificación en la UI del checkout impacta la **tasa de conversión de compra**.

---

1. **Analizar el dataset** `experiment_checkout_ui.csv` para identificar la métrica principal **conversion**.
   - La métrica **conversion** es 1 si el usuario completó la compra, 0 si no.    
2. **Plantear la hipótesis estadística**     
3. **Aplicar el test estadístico adecuado** 
4. **Interpretar el resultado**

---
Hipótesis estadística
   - **H₀ (Hipótesis nula):**  La tasa de conversión es igual en ambas páginas. Cualquier diferencia se debe al azar del muestreo.

   - **H₁ (Hipótesis alternativa):**  La tasa de conversión es diferente entre ambas páginas. Hay un factor que influye en la decisión de compra.
   
**Test estadístico:** prueba z para comparar proporciones 
**Nivel de significancia alpha:** alpha = 0.05

In [ ]:
# Libreria
from statsmodels.stats.proportion import proportions_ztest
# tu código aquí
experiment_checkout_ui = pd.read_csv('https://practicum-content.s3.amazonaws.com/datasets/experiment_checkout_ui.csv')

In [ ]:
experiment_checkout_ui.head()

In [ ]:
# Contar número de exitos y número total de registros
conversiones = experiment_checkout_ui.groupby('variante')['convirtio'].sum()
totales = experiment_checkout_ui.groupby('variante')['convirtio'].count()

# Pasar los valores a formato lista
exitos = [conversiones['tratamiento'], conversiones['control']]
observaciones = [totales['tratamiento'], totales['control']]

# Aplicar prueba y visualizar resultados
z_stat, p_value = proportions_ztest(exitos , observaciones)
print(f"Estadístico z: {z_stat}")
print(f"Valor p: {p_value}")

# Interpretar resultados
alpha = 0.05  # umbral de significancia
if p_value < alpha:
    print("Rechazamos la hipótesis nula: hay evidencia de una diferencia.")
else:
    print("No rechazamos la hipótesis nula: no hay evidencia suficiente de una diferencia.")

In [ ]:

conversion_rate = round((experiment_checkout_ui.groupby("variante")["convirtio"].sum() / experiment_checkout_ui.groupby("variante")["convirtio"].count()) * 100, 2)
print("tasa de conversion")
print(conversion_rate)
print("La diferencia entre las tasas de conversión no es estadísticamente significativa. Hay una diferencia pequeña (0.6%), pero el test dice que esa diferencia podría ser simplemente por azar, no por el cambio en la UI. ")

---

## 🔹 Paso 6: Comunicar los resultados (Dashboard en BI)

🎯 **Objetivo**:  
Crear un dashboard que muestre de manera clara y visual los resultados del análisis de ventas, costos, marketing y conversión. 

Se usarán los CSVs limpios del Paso 1:

- `orders_clean.csv`  
- `catalog_clean.csv`  
- `marketing_clean.csv`

---

1️⃣ Preparación de los datos
1. Cargar los CSVs en Power BI o Tableau.
2. Revisar relaciones:
   - `orders.nombre_producto` → `catalog.nombre_producto`
   - `orders.fecha_pedido` → tabla de fechas (crear calendario para análisis temporal)
   - `orders.fecha_pedido` → `dim_fecha.date`
3. Crear columnas calculadas necesarias
4. Crear tabla de fechas para poder calcular comparaciones YTD, YoY o períodos anteriores (`Previous Year`, `Previous Month`).

---

2️⃣ Dashboard 1: Overview Ejecutivo
**KPIs principales a mostrar:**
- Revenue total
- Profit total
- Gasto total en marketing
- Ticket promedio
- Cantidad promedio de productos por orden

**Visualizaciones sugeridas:**
- Tarjetas KPI para revenue, profit y gasto marketing
- Gráfico de líneas: evolución mensual de revenue o profit
- Gráfico de líneas YTD
- Gráfico de barras: revenue y profit por producto o categoría

---

 3️⃣ Dashboard 2: Detalle / Drill-through  
**Objetivo:** Permitir explorar los datos desde el KPI general hasta cada orden o producto.

**Visualizaciones sugeridas:**
- Tabla detallada de órdenes con:
  - producto, cantidad, revenue, cost, profit
  - color condicional (profit negativo en rojo, positivo en verde)
- Gráfico de barras por producto con medida `cantidad vendida`
- Drill-through: seleccionar un producto y ver todos los pedidos relacionados
- Filtros por fecha, categoría de producto, etc

---

## 🚀 Entrega Final

Comparte el acceso a tu Dashboard para revisión.   
Puedes entregar el Dashboard utilizando **Power BI o Tableau**.

Incluye **uno de los siguientes**:

- 🔗 Link público del dashboard publicado en **Power BI Service o Tableau Public / Tableau Cloud**
- 🔗 Link de **Google Drive o OneDrive** con el archivo del proyecto (`.pbix`) y los 3 csvs limpios.


### 📎 Enlace del Dashboard

In [ ]:
# link de google drive
https://drive.google.com/drive/folders/1EGBtnJtKIUTQzslIPdmo6Ima5NMa2UL1?usp=sharing